"""Canonical one-to-one mapping from website routes to notebooks."""

CATALOG = [
    ("Number Theory", "tribonacci", "Tribonacci Number"),
    ("Number Theory", "eulers-totient-function", "Euler's Totient Function"),
    ("Number Theory", "gaussian-primes", "Gaussian Primes"),
    ("Number Theory", "eisenstein-primes", "Eisenstein Primes"),
    ("Algebra", "quadratic-equation", "Quadratic Equation"),
    ("Algebra", "cubic-equation", "Cubic Equation"),
    ("Algebra", "quartic-equation", "Quartic Equation"),
    ("Algebra", "5th-root-of-unity", "5th Root of Unity"),
    ("Algebra", "7th-root-of-unity", "7th Root of Unity"),
    ("Algebra", "9th-root-of-unity", "9th Root of Unity"),
    ("Algebra", "17th-root-of-unity", "17th Root of Unity"),
    ("Mathematical Analysis", "order-of-partial-derivative", "The Order of Partial Derivative"),
    ("Mathematical Analysis", "polar-laplacian-2d", "Laplacian in Polar Coordinates"),
    ("Mathematical Analysis", "polar-laplacian-3d", "Laplacian in Spherical Coordinates"),
    ("Mathematical Analysis", "laplacian-hessian-jacobian", "Laplacian, Hessian, and Jacobian"),
    ("Mathematical Analysis", "eulers-formula", "Euler's Formula"),
    ("Mathematical Analysis", "fourier-series", "Fourier Series"),
    ("Mathematical Analysis", "leibniz-formula", "Leibniz Formula"),
    ("Geometry", "trigonometric-identities", "Trigonometric Identities"),
    ("Geometry", "gaussian-curvature-of-surface", "Gaussian Curvature of Surface"),
    ("Geometry", "riemann-curvature-tensor-of-S2", "Riemann Curvature Tensor of S²"),
    ("Geometry", "riemann-curvature-tensor-of-S3", "Riemann Curvature Tensor of S³"),
    ("Geometry", "riemann-curvature-tensor-of-S4", "Riemann Curvature Tensor of S⁴"),
    ("Geometry", "riemann-curvature-tensor-of-S5", "Riemann Curvature Tensor of S⁵"),
    ("Geometry", "riemann-curvature-tensor-of-S7", "Riemann Curvature Tensor of S⁷"),
    ("Geometry", "riemann-curvature-tensor-of-T2", "Riemann Curvature Tensor of T²"),
    ("Geometry", "riemann-curvature-tensor-of-S2xS3", "Riemann Curvature Tensor of S² × S³"),
    ("Geometry", "riemann-curvature-tensor-of-Schwarzschild-metric", "Schwarzschild Metric"),
    ("Geometry", "riemann-curvature-tensor-of-FLRW-metric", "Friedmann–Lemaître–Robertson–Walker Metric"),
    ("Geometry", "wedge-product", "Wedge Product"),
    ("Geometry", "exterior-derivative", "Exterior Derivative"),
    ("Geometry", "hodge-E3", "Hodge Operator of E³"),
    ("Geometry", "hodge-minkowski", "Hodge Operator of Minkowski Space"),
    ("Geometry", "hodge-laplacian-polar", "Hodge Laplacian of Polar Coordinates"),
    ("Geometry", "hodge-laplacian-spherical", "Hodge Laplacian of Spherical Coordinates"),
    ("Geometry", "curvature-form", "Curvature Form"),
    ("Geometry", "vector-analysis", "Vector Analysis"),
    ("Geometry", "yang-mills-equation-of-U1-gauge-theory", "Yang–Mills Equation of U(1) Gauge Theory"),
    ("Geometry", "euler-form-of-S2", "Euler Form of S²"),
    ("Geometry", "euler-form-of-T2", "Euler Form of T²"),
    ("Geometry", "chern-form-of-CP1", "Chern Form of a Complex Line Bundle over CP¹"),
    ("Geometry", "emr-highest-power-coefficient", "Highest-Power Coefficient in the EMR Curvature Formula"),
    ("Geometry", "emr-thurston-wcs-invariant", "Wodzicki–Chern–Simons Invariant on the Thurston Example"),
]

EXPECTED_SLUGS = {slug for _, slug, _ in CATALOG}
